#!/bin/bash

echo "Deleting bucket..."

# Check if a bucket name is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
aws s3api delete-bucket \
--bucket $BUCKET_NAME \
