#!/bin/bash

echo "===Putting object..."

# Check if a bucket name is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg ./bucket my-bucket-name"
    exit 1
fi

# Check if filename is provided
if [ -z "$2" ]; then
    echo "There needs to be a filename eg ./bucket my-bucket-name my-file-name"
    exit 1
fi


BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename $FILENAME)

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY
