#!/bin/bash
set -e

echo "Syncing files..."

# Check if a bucket name is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg ./bucket my-bucket-name"
    exit 1
fi

# Check if filename is provided
if [ -z "$2" ]; then
    echo "There needs to be a filename eg ./bucket my-bucket-name my-file-name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

#Where to put the files
OUTPUT_DIR="/tmp/s3-test-files"

rm -r $OUTPUT_DIR

#create output folder
mkdir -p $OUTPUT_DIR

NUMBER_OF_FILES=$(($RANDOM % 6 + 5))

for ((i=1; i<=$NUMBER_OF_FILES; i++)); do
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_${i}.txt"
    dd if=/dev/urandom of=$FILENAME bs=1024 count=$((($RANDOM % 1024 + 1))) 2> /dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
